nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['*'] # Allows requests from any origin
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: []
    max_age: 3600
    hosts: []