nelmio_cors:
  paths:
    "^/": ~
  defaults:
    allow_credentials: false
    allow_origin: ["*"]
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "OPTIONS"]
    expose_headers: ["Link"]
    max_age: 3600
