nelmio_cors:
  paths:
    '^/': # Adjust the path as needed
      allow_origin: ['*'] # Specify the allowed origins or use '*' for all origins
      allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      allow_headers: ['Content-Type', 'Authorization']
      max_age: 3600 # Adjust as needed
      hosts: []
      origin_regex: false
      forced_allow_origin_value: ~
