index:
  path: /
  controller: App\Controller\CurrencyRateController::index
mailer:
  path: /proseedMailer
  controller: App\Controller\ProseedMailerController::index
send:
  path: /proseedMailer/send
  controller: App\Controller\ProseedMailerController::send
